require "bundler/setup"
require "omniauth" 
require "omniauth-twitter" 
require "dm-core"
require "dm-migrations"
require "json"
require "haml"
require "sinatra"

require "./model"
require "./helpers"
require "./routes"